version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t image_collector:latest portal/image_app/image_collector/
      - docker tag image_collector:latest 117472117844.dkr.ecr.eu-north-1.amazonaws.com/image_collector:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 117472117844.dkr.ecr.eu-north-1.amazonaws.com/image_collector:latest