# Generated by Django 3.2 on 2021-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('label_id', models.CharField(max_length=20)),
                ('image_location', models.CharField(max_length=250)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('labels', models.TextField(max_length=250)),
                ('budget', models.IntegerField()),
                ('images_per_class', models.IntegerField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
