# Generated by Django 3.2 on 2021-04-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.RemoveField(
            model_name='image',
            name='label_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
        migrations.AddField(
            model_name='image',
            name='labels',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_location',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='labels',
            field=models.CharField(default='', max_length=200),
        ),
    ]
