# Generated by Django 3.2 on 2021-04-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210426_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_location',
        ),
        migrations.RemoveField(
            model_name='image',
            name='labels',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='labels',
            field=models.CharField(default='', help_text='Comma separated list. Eg: class1,class2,class3', max_length=200),
        ),
    ]
