# Generated by Django 3.2 on 2021-05-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='model_status',
            field=models.CharField(default='Not Trained', max_length=20),
        ),
    ]
