# Generated by Django 3.2 on 2021-05-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('predicted_label', models.CharField(default='', max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.project')),
            ],
        ),
    ]
